import { randomUUID } from 'crypto'
import './globals.scss'
import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import clsx from 'clsx'

const poppins = Poppins({
  subsets: ['latin', 'latin-ext', 'devanagari'],
  weight: ['400', '700', '100', '200', '300', '500', '600', '800', '900'],
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (

    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
