import EventProvider from '@providers/EventProvider'
import InformationProvider from '@providers/InformationProvider'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { Suspense } from 'react'
import './globals.scss'

const poppins = Poppins({
  subsets: ['latin', 'latin-ext', 'devanagari'],
  weight: ['400', '700', '100', '200', '300', '500', '600', '800', '900'],
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (

    <html lang="en">
      <head>
        <meta name="google-site-verification" content="ctYiVgIDqF93EFA9K-KPFNJsRgtSRLa3m8JrZsxpiw4" />
        <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
      </head>
      <body className={poppins.className}>
        <EventProvider />
        <Suspense>
          <InformationProvider />
        </Suspense>
        {children}
      </body>
    </html>
  )
}
